name: Compile blueprint

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Checkout project
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build Lean project
        uses: leanprover/lean-action@v1.4.0
        with:
          build: true
          lint: false
          mk_all-check: false
          use-github-cache: false

      - name: Generate LeanArchitect blueprint files
        run: ~/.elan/bin/lake build :blueprint

      - name: Compile blueprint only
        uses: leanprover-community/docgen-action@main
        with:
          blueprint: true
          build-page: false
          deploy: false